In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
titanic = pd.read_csv('../datasets/titanic_numeric.csv')
titanic.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_clean,Embarked_clean,Fare_clean,Fare_clean_tr,Title,Cabin_ind,Family_cnt
0,0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,147,2,22.0,3,7.2500,1.486167,11,0,1
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,81,0,38.0,0,71.2833,2.347457,12,1,1
2,2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,147,2,26.0,3,7.9250,1.512864,8,0,0
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,55,2,35.0,3,53.1000,2.213191,12,1,1
4,4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,147,2,35.0,3,8.0500,1.517606,11,0,0

In [3]:
features = titanic.drop(['PassengerId', 'Ticket', 'Name', 'Survived'], axis=1)
labels = titanic['Survived']

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size=0.5, random_state=42)

X_train.head()

,Unnamed: 0,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Age_clean,Embarked_clean,Fare_clean,Fare_clean_tr,Title,Cabin_ind,Family_cnt
570,570,2,1,62.0,0,0,10.5000,147,2,62.0,3,10.5000,1.600434,11,0,0
787,787,3,1,8.0,4,1,29.1250,147,1,8.0,2,29.1250,1.962697,7,0,5
74,74,3,1,32.0,0,0,56.4958,147,2,32.0,3,56.4958,2.240801,11,0,0
113,113,3,0,20.0,1,0,9.8250,147,2,20.0,3,9.8250,1.579307,8,0,1
635,635,2,0,28.0,0,0,13.0000,147,2,28.0,3,13.0000,1.670278,8,0,0

In [5]:
# Write out all data
X_train.to_csv('../datasets/titanic_split/train_features.csv', index=False)
X_val.to_csv('../datasets/titanic_split/val_features.csv', index=False)
X_test.to_csv('../datasets/titanic_split/test_features.csv', index=False)

y_train.to_csv('../datasets/titanic_split/train_labels.csv', index=False)
y_val.to_csv('../datasets/titanic_split/val_labels.csv', index=False)
y_test.to_csv('../datasets/titanic_split/test_labels.csv', index=False)

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
titanic_train = pd.read_csv('../datasets/titanic_split/train_features.csv')
titanic_val = pd.read_csv('../datasets/titanic_split/val_features.csv')
titanic_test = pd.read_csv('../datasets/titanic_split/test_features.csv')
titanic_train.head()

,Unnamed: 0,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Age_clean,Embarked_clean,Fare_clean,Fare_clean_tr,Title,Cabin_ind,Family_cnt
0,570,2,1,62.0,0,0,10.5000,147,2,62.0,3,10.5000,1.600434,11,0,0
1,787,3,1,8.0,4,1,29.1250,147,1,8.0,2,29.1250,1.962697,7,0,5
2,74,3,1,32.0,0,0,56.4958,147,2,32.0,3,56.4958,2.240801,11,0,0
3,113,3,0,20.0,1,0,9.8250,147,2,20.0,3,9.8250,1.579307,8,0,1
4,635,2,0,28.0,0,0,13.0000,147,2,28.0,3,13.0000,1.670278,8,0,0

In [8]:
# Fit the scaler on the training data
scaler = StandardScaler()
scaler.fit(titanic_train)

StandardScaler()

In [9]:
# scalin training test and val
features = titanic_train.columns

titanic_train[features] = scaler.transform(titanic_train[features])
titanic_val[features] = scaler.transform(titanic_val[features])
titanic_test[features] = scaler.transform(titanic_test[features])

titanic_train.head()

,Unnamed: 0,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Age_clean,Embarked_clean,Fare_clean,Fare_clean_tr,Title,Cabin_ind,Family_cnt
0,0.459473,-0.408652,0.737125,2.258185,-0.464063,-0.468427,-0.412724,0.450064,0.573494,2.570771,0.545364,-0.483840,-0.446199,0.430223,-0.544166,-0.540385
1,1.297138,0.803682,0.737125,-1.469145,2.692745,0.794906,-0.066661,0.450064,-0.718682,-1.673694,-0.334468,-0.046993,0.373863,-1.784129,-0.544166,2.277639
2,-1.455190,0.803682,0.737125,0.187446,-0.464063,-0.468427,0.441904,0.450064,0.573494,0.212735,0.545364,0.594986,1.003414,0.430223,-0.544166,-0.540385
3,-1.304642,0.803682,-1.356623,-0.640849,0.325139,-0.468427,-0.425266,0.450064,0.573494,-0.730480,0.545364,-0.499672,-0.494025,-1.230541,-0.544166,0.023220
4,0.710387,-0.408652,-1.356623,-0.088652,-0.464063,-0.468427,-0.366273,0.450064,0.573494,-0.101670,0.545364,-0.425203,-0.288093,-1.230541,-0.544166,-0.540385

In [10]:
# Define the lists of features 
raw_original_features = ['Pclass', 'Sex', 'Age_clean', 'SibSp', 'Parch', 'Fare', 'Cabin', 'Embarked']
cleaned_original_features = ['Pclass', 'Sex', 'Age_clean', 'SibSp', 'Parch', 'Fare_clean', 'Cabin', 'Embarked_clean']
all_features = ['Pclass', 'Sex', 'Age_clean', 'SibSp', 'Parch', 'Fare_clean', 'Fare_clean_tr', 'Cabin', 'Cabin_ind', 'Embarked_clean', 'Title', 'Family_cnt']
reduced_features = ['Pclass', 'Sex', 'Age_clean', 'Family_cnt', 'Fare_clean_tr', 'Cabin_ind', 'Title']

In [11]:
# write out final data for each feature set
titanic_train[raw_original_features].to_csv('../datasets/final_data/train_features_raw.csv', index=False)
titanic_val[raw_original_features].to_csv('../datasets/final_data/val_features_raw.csv', index=False)
titanic_test[raw_original_features].to_csv('../datasets/final_data/test_features_raw.csv', index=False)

titanic_train[cleaned_original_features].to_csv('../datasets/final_data/train_features_cleaned.csv', index=False)
titanic_val[cleaned_original_features].to_csv('../datasets/final_data/val_features_cleaned.csv', index=False)
titanic_test[cleaned_original_features].to_csv('../datasets/final_data/test_features_cleaned.csv', index=False)


titanic_train[all_features].to_csv('../datasets/final_data/train_features_all.csv', index=False)
titanic_val[all_features].to_csv('../datasets/final_data/val_features_all.csv', index=False)
titanic_test[all_features].to_csv('../datasets/final_data/test_features_all.csv', index=False)

titanic_train[reduced_features].to_csv('../datasets/final_data/train_features_reduced.csv', index=False)
titanic_val[reduced_features].to_csv('../datasets/final_data/val_features_reduced.csv', index=False)
titanic_test[reduced_features].to_csv('../datasets/final_data/test_features_reduced.csv', index=False)

In [12]:
# Read in all labels
titanic_train_labels = pd.read_csv('../datasets/titanic_split/train_labels.csv')
titanic_val_labels = pd.read_csv('../datasets/titanic_split/val_labels.csv')
titanic_test_labels = pd.read_csv('../datasets/titanic_split/test_labels.csv')

In [ ]:
titanic_train_labels